.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py profiling

clean:
	rm -f profiling.py profiling.md Doxyfile
	rm -rf html

cleaner:
	rm -f profiling.ipynb profiling.py profiling.md Doxyfile
	rm -rf html
